name: Update Dashboard Data

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: npm install
        
    - name: Fetch latest data
      env:
        GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
        GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
        SHEET_ID: ${{ secrets.SHEET_ID }}
      run: |
        mkdir -p data
        node scripts/fetchData.js
        cp -r data/* docs/data/
        
    - name: Check for changes
      id: check_changes
      run: |
        git status
        echo "Has changes: $(git status --porcelain)"
        echo "::set-output name=has_changes::$(git status --porcelain | wc -l)"
        
    - name: Commit and push if changed
      if: steps.check_changes.outputs.has_changes > 0
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add data/* docs/data/*
        git commit -m "Update dashboard data [skip ci]"
        git push
